# Freely modify this file to change what the user can modify
# The key is the command which will cause that entityType to fire, ie "/giver cat"
# EntityName rules are ::
# 	MaterialType [Link : http://jd.bukkit.org/doxygen/d9/db0/Material_8java_source.html] OR EntityType [Link : http://jd.bukkit.org/doxygen/d6/d7b/EntityType_8java_source.html]

ignoreSpawnLimitsIfAdmin: false 
spawnableTypes:
  cat:
    minecraftName: Ozelot
    spawnLimits:
      normal: 4
      super: 10
  wolf:
    minecraftName: Wolf
    spawnLimits:
      normal: 4
      super: 10
  golem:
    minecraftName: VillagerGolem
    spawnLimits:
      normal: 4
      super: 10
  cart:
    minecraftName: Minecart
    spawnLimits:
      normal: 2
      super: 4
  villager:
    minecraftName: Villager
    spawnLimits:
      normal: 4
      super: 10
  pig:
    minecraftName: Pig
    spawnLimits:
      normal: 4
      super: 10
  sheep:
    minecraftName: Sheep
    spawnLimits:
      normal: 4
      super: 10
  cow:
    minecraftName: Cow
    spawnLimits:
      normal: 4
      super: 10
  chicken:
    minecraftName: Chicken
    spawnLimits:
      normal: 4
      super: 10