# Freely modify this file to change what the user can modify
# The key is the command which will cause that entityType to fire, ie "/giver cat"
# EntityName rules are ::
# 	MaterialType [Link : http://jd.bukkit.org/doxygen/d9/db0/Material_8java_source.html]
# OR
#	EntityType [Link : http://jd.bukkit.org/doxygen/d6/d7b/EntityType_8java_source.html]

ignoreSpawnLimitsIfAdmin: false

spawnableTypes:
  cat:
    minecraftName: Ozelot
    spawnLimitPerHour: 4
  wolf:
    minecraftName: Wolf
    spawnLimitPerHour: 4
  golem:
    minecraftName: VillagerGolem
    spawnLimitPerHour: 4
  cart:
    minecraftName: Minecart
    spawnLimitPerHour: 2
  villager:
    minecraftName: Villager
    spawnLimitPerHour: 4
  pig:
    minecraftName: Pig
    spawnLimitPerHour: 4
  sheep:
    minecraftName: Sheep
    spawnLimitPerHour: 4
  cow:
    minecraftName: Cow
    spawnLimitPerHour: 4
  chicken:
    minecraftName: Chicken
    spawnLimitPerHour: 4
  sand:
    minecraftName: Sand
    spawnLimitPerHour: 5