name: Giver 
version: 1.0
author: Alan Foster
website: https://github.com/AlanFoster/Giver

main: me.alanfoster.giver.Giver
   
permissions:
  giver.normal:
    description: Normal user operations
    default: true
  giver.super:
    description: Super user operations!
    default: false
    
# Commands defined in config.yml